### ISSUE TITLE
 TypeError: string.toString(...).replaceAll is not a function

### ISSUE THREAD

**Issue by Lucas-C** [saibotsivad/ajv-openapi-compile#1]
Hi.

I would just like to report that I get the following stacktrace while using your tool:

```
$ node --version
v14.19.0

$ npm install ajv-openapi-compile --save-dev
+ ajv-openapi-compile@0.0.14

$ npx ajv-openapi-compile --definition=openapi.yaml --schema=openapi-schema.js

(node:28686) UnhandledPromiseRejectionWarning: TypeError: string.toString(...).replaceAll is not a function
    at encode (file:///opt/test/node_modules/ajv-openapi-compile/src/generate.js:9:44)
    at file:///opt/test/node_modules/ajv-openapi-compile/src/generate.js:26:33
    at Array.map (<anonymous>)
    at addToTree (file:///opt/test/node_modules/ajv-openapi-compile/src/generate.js:26:24)
    at generate (file:///opt/test/node_modules/ajv-openapi-compile/src/generate.js:42:3)
    at compile (file:///opt/test/node_modules/ajv-openapi-compile/src/index.js:11:25)
    at work (file:///opt/test/node_modules/ajv-openapi-compile/bin.js:36:25)
    at file:///opt/test/node_modules/ajv-openapi-compile/bin.js:40:1
    at ModuleJob.run (internal/modules/esm/module_job.js:183:25)
    at async Loader.import (internal/modules/esm/loader.js:178:24)
```

**Comment by saibotsivad** [comment]
Curious 🤔 can you post in the YAML file that's causing the problem?

**Comment by Lucas-C** [comment]
Sorry but not right now nor in the near future.
I understand that without a minimal YAML file to reproduce the problem, this bug report is not very helpful.
Feel free to close this issue as a consequence.
This project looked very promising, but I ended up using another tool/approach.

**Comment by saibotsivad** [comment]
Closing since I don't have enough information to act on.
